### ISSUE TITLE
Be aware of sbt-less version \gt 1.0.6

### ISSUE THREAD

**Issue by renexdev** [webjars/sample-play2#8]
Just a comment, if you change sbt-less verision in
addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.6")
to version 1.1.0 there is an unexpected exception
some traks of the issue:
JsTaskFailure: /yourprojectpath/project/target/node-modules/webjars/less/lib/less/index.js:13
        functions: require('./functions')(environment),
                                         ^
TypeError: object is not a function
    at module.exports (/yourprojectpath/project/target/node-modules/webjars/less/lib/less/index.js:13:42)
    at Object.<anonymous> (/yourprojectpath/project/target/node-modules/webjars/less/lib/less-node/index.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (yourprojectpath/project/target/node-modules/webjars/less/index.js:1:80)
I do not know the reason. I found the solution at https://github.com/sbt/sbt-less/issues/68.
Cheers,
ReneX

**Comment by jamesward** [comment]
Thanks for the heads up!

**Comment by renexdev** [comment]
Thks to u! For all the contribution and for all I've learn on Scala & Play!
Cheers

Dr. Rene Cejas Bolecek
ncejas@cab.cnea.gov.ar
Low Temperatures Laboratory- Centro Atomico Bariloche,
Rio Negro, ARGENTINA
